### ISSUE TITLE
Close Method Failing

### ISSUE THREAD

**Issue by philipcunningham** [HashNuke/arduino#4]
The close method doesn't seem to reset the serial connection and I have to disconnect and reconnect the Arduino. Is there a way around this? I'm running Ubuntu 10.10.

**Comment by HashNuke** [comment]
close method is a part of the gem. However I did have this problem sometimes when I was on Ubuntu. I haven't played with this gem since I got my Mac a couple months back. I'll look into this today evening.

However, if you think you have a solution, fork, fix and send me a pull request and I'll try that out too.

**Comment by philipcunningham** [comment]
I'm not entirely sure, to be honest. I tried a variety of things (Serial.end() for '5'.chr). What do you think's the best way to approach solving it?

**Comment by philipcunningham** [comment]
Also, I have noticed that I can reset the serial port by opening the arduino serial monitor.
